---
title: "Simple Quandl Commodities Flexdb"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    #vertical_layout: scroll
    orientation: rows
    source_code: embed
---

```{r setup, include=FALSE}
library(Quandl)
library(dplyr)
library(xts)
library(lubridate)
library(forecast)
library(dygraphs)
```

Inputs{.sidebar}
--------------------------------

```{r}
# Notice a tradeoff here: we're making it easy on our users because they don't need to 
# remember the naming conventions. But, we're also forced to severely limit their choices. 
# On page two, we'll see what it looks like to be more flexible but less efficient.

dataChoices <- c("WTI oil" = "FRED/DCOILWTICO", #fred data from federal reserve
                "Copper" = "ODA/PCOPP_USD", # world bank
                "Gold" = "BUNDESBANK/BBK01_WT5511")

 selectInput("dataSet",
              "Commodity",
             choices = dataChoices, #freddie mac
                         #"BIS",  #bank of intl settlements
                         #"ODA",  #IMF
                         #"ISM"), #Inst of supply management
             selected = "WTI oil")
 
frequencyChoices <- c("days" = "daily",
                      "weeks" = "weekly", 
                      "months" = "monthly")
                     
selectInput("frequency",
            "freq",
            choices = frequencyChoices, 
            selected = "months")
                     
#selectInput("country", "Select country", list(
#  "Europe" = c("Germany", "Spain"),
#  "North America" = c("Canada", "United States" = "USA")
#))

dateRangeInput("dateRange",
               "Date range",
               start = "1980-01-01",
               end   = "2016-12-31")

numericInput("periods", "Months to Forecast", 6, min = 1, max = 12)

#dataSource <- toupper(gsub(" ", "", input$dataSource, fixed = TRUE))
commodity <- reactive({
  dataSet <- toupper(gsub(" ", "", input$dataSet, fixed = TRUE))
      ##if you think you'll use this more than 50 times per day, you'll need an api key
      ##Quandl.api_key(as.character(input$api_key))
      
#inst <- paste(dataSource, dataSet, sep="/")
      
commodity <- Quandl(dataSet,
               start_date = format(input$dateRange[1]),
               end_date = format(input$dateRange[2]),
               order = "asc",
               type = "xts",
               collapse = as.character(input$frequency)
              )
})

combined_xts <- reactive({
  forecasted <- forecast(commodity(), h = input$periods)
  forecast_dataframe <- data.frame(date = seq(input$dateRange[2], 
                                          #days or weeks    
                                           by = names(frequencyChoices[frequencyChoices == input$frequency]), 
                                          length.out = input$periods),
                                Forecast = forecasted$mean,
                                Hi_95 = forecasted$upper[,2],
                                Lo_95 = forecasted$lower[,2])
  forecast_xts <- xts(forecast_dataframe[,-1], order.by = forecast_dataframe[,1])
  combined_xts <- cbind(commodity(), forecast_xts)

# Add a nicer name for the first column.

  colnames(combined_xts)[1] <- "Actual"
  combined_xts
})
```


Row
-------------------------------------
    
### Chart 1
    
```{r}
dygraphOutput("commodity")

output$commodity <- renderDygraph({
  dygraph(commodity(), 
          main = paste("Price history of", names(dataChoices[dataChoices==input$dataSet]), 
                       sep = " ")) %>%
    dyAxis("y", label = "$") %>%
    dyOptions(axisLineWidth = 1.5, fillGraph = TRUE, drawGrid = TRUE)
})

```

Row
-------------------------

### Chart 2

```{r}

dygraphOutput("forecasted")

output$forecasted <- renderDygraph({
dygraph(combined_xts(), 
        main = paste(names(dataChoices[dataChoices==input$dataSet]), 
                     ": Historical and Forecast", sep = "")) %>%
  # Add the actual series
  dySeries("Actual", label = "Actual") %>%
  # Add the three forecasted series
  dySeries(c("Lo_95", "Forecast", "Hi_95"))
})
```

